#!/bin/bash

LXTERMINAL=`ps -ef|grep lxterminal|grep -v "grep"|awk '{print $2}'`
if [ -n "$LXTERMINAL" ]; then kill -9 $LXTERMINAL; fi
sleep 10

/home/pi/bin/check_hard_drives

if [[ $(find /mnt/HDD/PI\ backup/ -name "sd_card_backup.img" -mtime +30 -print) ]]; then
	echo "MOUNT AND BINDFS (ACCORDING TO ~/bin/mount_backup_drive BEFORE RUNNING THIS SCRIPT FOR RSYNC TO WORK"
	sudo dd bs=1M if=/dev/mmcblk0p2 of=/mnt/HDD/PI\ backup/sd_card_backup.img
	sudo rsync --archive --delete --times --verbose /etc/ /mnt/HDD/PI\ backup/etc/
	sudo rsync --archive --delete --times --verbose /home/pi/bin/ /mnt/HDD/PI\ backup/bin/
	sudo chown -R pi /mnt/HDD/PI\ backup
	sudo chgrp -R pi /mnt/HDD/PI\ backup
fi

/home/pi/bin/home_backup_just_rclone

# /home/pi/bin/home_backup_rsync_part

