#!/bin/bash

find /mnt/HDD/ -mindepth 1 -maxdepth 1 -type d -not -path '*/\.*' | while read n; do
	m=$(echo "$n"|sed 's/\/mnt\/HDD\///')
	if [[ "$n" != *"to_file"* && "$m" != "films" && "$n" != *"tmp"* ]]; then
		echo "rclone'ing" "$n" "$m"
#		nice -n 20 rclone --delete-excluded --transfers 3 --checkers 3 --tpslimit 3 --drive-chunk-size 64M --fast-list --max-size 50G --verbose sync "$n" gdrv:Home/"$m"
#        	nice -n 20 rclone --delete-excluded --low-level-retries 100 --transfers 3 --checkers 3 --tpslimit 3 --drive-chunk-size 64M --fast-list --verbose --log-file /tmp/rclone_"$m"_logfile sync "$n" gdrv:Home/"$m"
               	nice -n 20 rclone --bwlimit 1M --delete-excluded --transfers 3 --checkers 3 --tpslimit 3 --drive-chunk-size 64M --fast-list --verbose --log-file /tmp/rclone_"$m"_logfile sync "$n" gdrv:Home/"$m"
	fi
done

